apiVersion: v1
kind: Service
metadata:
  name: wordpress-stag
  namespace: staging
  labels:
    app: wordpress-stag
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress-stag
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: staging
  labels:
    app: wordpress-stag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-stag
  namespace: staging
  labels:
    app: wordpress-stag
spec:
  selector:
    matchLabels:
      app: wordpress-stag
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-stag
        tier: frontend
    spec:
      containers:
      - image: wordpress:php7.4-apache
        name: wordpress-stag
        env:
        - name: WORDPRESS_DB_HOST
          value: cilsydb.ct6gyzehincn.ap-southeast-1.rds.amazonaws.com
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-wp
              key: password
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-wp
              key: username
        - name: WORDPRESS_DB_NAME
          value: wordpress-stag
        ports:
        - containerPort: 80
          name: wordpress-stag
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-wp
  namespace: staging
type: Opaque
stringData:
  username: root
  password: Admin123
  database: stagwp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: staging
  name: wordpress-stag
  annotations:
   # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: s-blog.sarisalju.com
    http:
      paths:
      #- path: /
      - backend:
          serviceName: wordpress-stag
          servicePort: 80
